### PR TITLE
Port the Linux release script to Python

### PR DESCRIPTION
**Pull request by DavidZemon**
The new script supports a user-configurable build directory as well as various other configuration options, allowing the user more freedom in how their computer is set up. It will work whether or not PropGCC is installed. If PropGCC is not installed, it will automatically download the latest release from TeamCity. If the latest release is undesirable (for instance, when creating an official release to be supported by Parallax, a pre-defined installation path for a Parallax-support version of PropGCC can be provided as a command line argument.

I've also made the PropLoader and SimpleIDE workspace as Git submodules, making the packaging script a bit simpler and providing a bit better control over which versions of each of those products are packaged with SimpleIDE.

My fork is being watched and built on TeamCity and is available for download here: https://ci.zemon.name/project.html?projectId=SimpleIDE&tab=projectOverview&guest=1

### CODE REVIEW

**Comment by DavidZemon** [comment]
Oh, and I would _strongly_ encourage using the "Squash and merge" option for this. Got some useless commit messages in there :)

**Comment by DavidZemon** [comment]
I was premature in opening this request. There are still bugs that I'm working through apparently. I'll comment back here once it's actually working.

**Comment by DavidZemon** [comment]
With the latest commit, I'm able to start and run SimpleIDE after installing via `setup.sh`. I can go through a few of the menus and compile the Welcome program. It seems to load to my Activity Board (rev A) without error, but nothing shows up on the terminal. From the stdout logs, I see the command that is being invoked to do the load. Indeed, when I run that command manually, it proceeds without error but then fails to display anything useful. When I invoked the same command but with `propeller-load` rather than `proploader`, same exact issue. I then confirmed that `propeller-load` is functional by verifying that it correctly loads and runs an app from PropWare. But I'm unable to get the Welcome project to run on the activity board.

Any ideas where I should look?

As always, the package can be downloaded from here: http://david.zemon.name:8111/project.html?projectId=SimpleIDE&tab=projectOverview&guest=1

**Comment by chrisl8** [comment]
@DavidZemon I am seeing this same issue: The Welcome program seems to load to my Activity Board without error, but nothing shows up on the terminal.

Also, I find that the drop down list for selecting the port is broken. it won't actually "drop down". I can only select it and then use the up/down arrows to pick the port.

**Comment by DavidZemon** [comment]
Closing this since it looks like no one cares enough to test/merge/release this and i'm tired of seeing it in my PR list.

**Pull request closed without merging**
